version: "3.8"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rustshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5435:5432
    profiles:
      - only-db
    networks:
      - shop_network
volumes:
  postgres-data:

networks:
  shop_network: